//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_Template_1___Web_Forms {
	
	
	public partial class Login {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected System.Web.UI.WebControls.TextBox txtUsername;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.CheckBox cbxRememberMe;
		
		protected System.Web.UI.WebControls.Button btnLogin;
		
		protected System.Web.UI.WebControls.Label lblLoginAlert;
		
		protected System.Web.UI.WebControls.TextBox txtNewUser;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtFN;
		
		protected System.Web.UI.WebControls.TextBox txtLN;
		
		protected System.Web.UI.WebControls.TextBox txtNewPwd;
		
		protected System.Web.UI.WebControls.TextBox txtRptPwd;
		
		protected System.Web.UI.WebControls.Button btnSignup;
		
		protected System.Web.UI.WebControls.Label lblRegAlert;
	}
}
